name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: preview
    displayName: Preview
    dependsOn: []
    variables:
      - group: terraform-ap-southeast-2-production
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: preview
          serviceConnectionName: $(terraformServiceConnectionName)
          stateBucketName: $(terraformStateBucketName)
          stateLockTableName: $(terraformStateLockTableName)
          region: $(terraformRegion)

  - stage: production
    displayName: Production
    dependsOn: []
    variables:
      - group: terraform-ap-southeast-2-production
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: production
          serviceConnectionName: $(terraformServiceConnectionName)
          stateBucketName: $(terraformStateBucketName)
          stateLockTableName: $(terraformStateLockTableName)
          region: $(terraformRegion)